"""«Мои игры» для окна программы: список игр с состоянием русификации (кэш + фоновый поиск)."""

from __future__ import annotations

import json
import logging
import re
import threading
import time
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from .. import library, paths
from ..core.backup import GameBackup

log = logging.getLogger("russificator.games")

LIVE_FILE = "BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt"


def live_count(game: Path) -> int:
    """Сколько строк перевела живая «доводка» в игре (Unity/XUnity) — насколько далеко заранее
    подготовленный перевод от 100 %."""
    f = Path(game) / LIVE_FILE
    try:
        with f.open("r", encoding="utf-8", errors="replace") as fh:
            return sum(1 for line in fh if "=" in line and not line.lstrip().startswith("//"))
    except OSError:
        return 0


def status(game: Path) -> Dict[str, Any]:
    """Состояние русификации папки игры (быстро: манифест бэкапа и stat файлов)."""
    from ..core.package import translator_title
    b = GameBackup(Path(game))
    if not b.exists:
        return {"russified": False}
    ok, broken = b.check()
    info = b.info or {}
    pkg = info.get("package") or {}
    return {
        "russified": True, "intact": ok, "broken": len(broken), "from_package": bool(pkg),
        "translator": pkg.get("translator") if pkg else translator_title(str(info.get("translator", ""))),
        "date": info.get("date") or info.get("installed") or "",
        "translated": info.get("translated"), "total": info.get("total"),
        "live": live_count(Path(game)),
    }


def russified_dirs() -> List[str]:
    """Папки игр из проектов программы (что уже переводилось)."""
    out = []
    for f in paths.sub("projects").glob("*/project.json"):
        try:
            with f.open("r", encoding="utf-8") as fh:
                head = fh.read(4096)
            m = re.search(r'"game_dir"\s*:\s*"((?:[^"\\]|\\.)*)"', head)
            if m:
                out.append(json.loads(f'"{m.group(1)}"'))
        except (OSError, ValueError):
            continue
    return out


class Library:
    """Список игр: мгновенно из кэша, свежий — фоновым поиском."""

    def __init__(self, emit: Callable[[Dict[str, Any]], None]):
        self.emit = emit
        self._lock = threading.Lock()
        self._thread: Optional[threading.Thread] = None
        self.games: List[Dict[str, Any]] = []
        self.scanned_at = 0.0
        self._load_cache()

    @property
    def cache_file(self) -> Path:
        return paths.cache_dir() / "library.json"

    @property
    def scanning(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    def _load_cache(self) -> None:
        try:
            data = json.loads(self.cache_file.read_text(encoding="utf-8"))
            self.games = [g for g in data.get("games", []) if isinstance(g, dict) and g.get("path")]
            self.scanned_at = float(data.get("scanned_at", 0))
        except (OSError, ValueError):
            self.games, self.scanned_at = [], 0.0

    def _save_cache(self) -> None:
        try:
            tmp = self.cache_file.with_suffix(".tmp")
            tmp.write_text(json.dumps({"scanned_at": self.scanned_at, "games": self.games}, ensure_ascii=False),
                           encoding="utf-8")
            tmp.replace(self.cache_file)
        except OSError as exc:
            log.warning("кэш списка игр не записан: %s", exc)

    def snapshot(self, cfg: Dict[str, Any]) -> Dict[str, Any]:
        hidden = {library._norm(Path(p)) for p in cfg.get("library_hidden") or []}
        games = [g for g in self.games if library._norm(Path(g["path"])) not in hidden]
        return {"games": games, "scanned_at": self.scanned_at, "scanning": self.scanning}

    def refresh_status(self, path: str) -> Optional[Dict[str, Any]]:
        """Обновить состояние одной игры (после русификации/отката)."""
        key = library._norm(Path(path))
        with self._lock:
            for g in self.games:
                if library._norm(Path(g["path"])) == key:
                    g.update(status(Path(g["path"])))
                    self._save_cache()
                    return g
        return None

    def scan(self, cfg: Dict[str, Any]) -> bool:
        """Запустить фоновый поиск. False — поиск уже идёт."""
        with self._lock:
            if self.scanning:
                return False
            self._thread = threading.Thread(target=self._scan, args=(dict(cfg),), name="library", daemon=True)
            self._thread.start()
        return True

    def _scan(self, cfg: Dict[str, Any]) -> None:
        started = time.monotonic()
        try:
            found = library.discover(
                extra_folders=cfg.get("library_folders") or [],
                manual=cfg.get("library_manual") or [],
                russified=russified_dirs(),
                status=lambda name: self.emit({"type": "library_progress", "message": f"Ищу игры: {name}…"}))
            games = []
            for e in found:
                d = e.to_dict()
                try:
                    d.update(status(Path(e.path)))
                except Exception as exc:  # noqa: BLE001
                    log.debug("состояние %s: %s", e.path, exc)
                games.append(d)
            with self._lock:
                self.games = games
                self.scanned_at = time.time()
                self._save_cache()
            log.info("Мои игры: %d за %.1f с", len(games), time.monotonic() - started)
            self.emit({"type": "library", "final": True, **self.snapshot(cfg), "scanning": False})
        except Exception as exc:  # noqa: BLE001
            log.exception("поиск игр упал")
            self.emit({"type": "library", "final": True, "error": str(exc), **self.snapshot(cfg), "scanning": False})

    def add(self, path: str) -> Dict[str, Any]:
        p = Path(path)
        e = library.GameEntry(path=str(p), title=p.name, source="manual", engine=library.quick_engine(p))
        exe = library.main_exe(p)
        e.exe = str(exe) if exe else ""
        e.sources = ["manual"]
        d = e.to_dict()
        d.update(status(p))
        key = library._norm(p)
        with self._lock:
            self.games = [g for g in self.games if library._norm(Path(g["path"])) != key] + [d]
            self.games.sort(key=lambda g: str(g.get("title", "")).lower())
            self._save_cache()
        return d


def steam_cover_file(appid: str) -> Optional[Path]:
    """Обложка из кэша Steam (работает без интернета)."""
    root = library.steam_root()
    if root is None or not re.fullmatch(r"\d+", appid or ""):
        return None
    cache = root / "appcache" / "librarycache"
    for p in (cache / f"{appid}_header.jpg", cache / appid / "header.jpg", cache / f"{appid}_library_hero.jpg"):
        if p.is_file():
            return p
    d = cache / appid
    if d.is_dir():
        for p in d.rglob("header*.jpg"):
            return p
    return None
